fragment LessonPeriodListItem on LessonPeriod {
  id
  name
  dispOrder
}

query allLessonPeriods {
  allLessonPeriods {
    ...LessonPeriodListItem
  }
}

mutation createLessonPeriod($input: LessonPeriodInput!) {
  createLessonPeriod(input: $input) {
    id
  }
}

mutation updateLessonPeriod($lessonPeriodId: String!, $input: LessonPeriodInput!) {
  updateLessonPeriod(lessonPeriodId: $lessonPeriodId, input: $input) {
    id
  }
}

mutation deleteLessonPeriod($lessonPeriodId: String!) {
  deleteLessonPeriod(lessonPeriodId: $lessonPeriodId)
}
