type Area {
  companyId: String
  "ISO-8601"
  createdAt: DateTime
  "ISO-8601"
  deletedAt: DateTime
  displayOrder: Int
  id: String
  name: String
  "ISO-8601"
  updatedAt: DateTime
}

type Employee {
  companyId: String
  "ISO-8601"
  createdAt: DateTime
  "ISO-8601"
  deletedAt: DateTime
  email: String
  genderCode: String
  id: String
  isAdmin: Boolean
  isDeleted: Boolean
  "ISO-8601"
  lastLoginAt: DateTime
  name: String
  password: String
  "ISO-8601"
  passwordSetAt: DateTime
  status: String
  "ISO-8601"
  updatedAt: DateTime
}

type EmployeeInviteResult {
  email: String
  employeeId: String
  "ISO-8601"
  expiresAt: DateTime
  inviteUrl: String
}

type Gender {
  code: String
  name: String
  sortOrder: Int
}

type Lead {
  companyId: String
  "ISO-8601"
  createdAt: DateTime
  "ISO-8601"
  deletedAt: DateTime
  email: String
  id: String
  "ISO-8601"
  inquiryAt: DateTime
  location: Location
  locationId: String
  "ISO-8601"
  lostAt: DateTime
  lostReason: String
  name: String
  note: String
  phone: String
  source: String
  status: String
  "ISO-8601"
  updatedAt: DateTime
}

type Location {
  address: String
  area: Area
  areaId: String
  companyId: String
  "ISO-8601"
  createdAt: DateTime
  "ISO-8601"
  deletedAt: DateTime
  displayOrder: Int
  id: String
  isDefault: Boolean
  name: String
  prefecture: Prefecture
  prefectureCode: String
  "ISO-8601"
  updatedAt: DateTime
  zipCode: String
}

type Member {
  address: String
  "ISO-8601"
  birthDate: Date
  companyId: String
  "ISO-8601"
  createdAt: DateTime
  "ISO-8601"
  deletedAt: DateTime
  email: String
  id: String
  "ISO-8601"
  joinedAt: Date
  lead: Lead
  leadId: String
  lineDisplayName: String
  location: Location
  locationId: String
  name: String
  note: String
  phone: String
  resignationNote: String
  resignationReasonCode: String
  "ISO-8601"
  resignedAt: Date
  source: String
  status: String
  "ISO-8601"
  updatedAt: DateTime
}

"Mutation root"
type Mutation {
  createArea(input: AreaInput): Area
  createEmployee(input: EmployeeInput): Employee
  createLead(input: LeadInput): Lead
  createLocation(input: LocationInput): Location
  createMember(input: MemberInput): Member
  deleteArea(areaId: String!): Boolean!
  deleteEmployee(employeeId: String!): Boolean!
  deleteLead(leadId: String!): Boolean!
  deleteLocation(locationId: String!): Boolean!
  deleteMember(memberId: String!): Boolean!
  issueEmployeeInvite(input: EmployeeInviteInput): EmployeeInviteResult
  updateArea(areaId: String!, input: AreaInput): Area
  updateAreaOrders(inputs: [AreaOrderInput]): Boolean!
  updateEmployee(employeeId: String!, input: EmployeeInput): Employee
  updateLead(input: LeadInput, leadId: String!): Lead
  updateLocation(input: LocationInput, locationId: String!): Location
  updateMember(input: MemberInput, memberId: String!): Member
  updateOwnAccount(input: OwnAccountUpdateInput): Employee
}

type Page_Area {
  contents: [Area]
  limit: Int!
  offset: Int!
  totalCount: BigInteger!
  totalPages: Int!
}

type Page_Employee {
  contents: [Employee]
  limit: Int!
  offset: Int!
  totalCount: BigInteger!
  totalPages: Int!
}

type Page_Lead {
  contents: [Lead]
  limit: Int!
  offset: Int!
  totalCount: BigInteger!
  totalPages: Int!
}

type Page_Location {
  contents: [Location]
  limit: Int!
  offset: Int!
  totalCount: BigInteger!
  totalPages: Int!
}

type Page_Member {
  contents: [Member]
  limit: Int!
  offset: Int!
  totalCount: BigInteger!
  totalPages: Int!
}

type Prefecture {
  code: String
  name: String
  sortOrder: Int
}

"Query root"
type Query {
  allAreas: [Area]
  allEmployees: [Employee]
  allGenders: [Gender]
  allLeads: [Lead]
  allLocations: [Location]
  allMembers: [Member]
  allPrefectures: [Prefecture]
  areaById(areaId: String!): Area
  areaPagination(filter: AreaFilterInput, pagination: Pagination): Page_Area
  employeeById(employeeId: String!): Employee
  employeePagination(filter: EmployeeFilterInput, pagination: Pagination): Page_Employee
  leadById(leadId: String!): Lead
  leadPagination(filter: LeadFilterInput, pagination: Pagination): Page_Lead
  locationById(locationId: String!): Location
  locationPagination(filter: LocationFilterInput, pagination: Pagination): Page_Location
  memberById(memberId: String!): Member
  memberPagination(filter: MemberFilterInput, pagination: Pagination): Page_Member
}

"Scalar for BigDecimal"
scalar BigDecimal

"Scalar for BigInteger"
scalar BigInteger

"Scalar for Date"
scalar Date

"Scalar for DateTime"
scalar DateTime

input AreaFilterInput {
  name: String
}

input AreaInput {
  dispOrder: Int
  name: String!
}

input AreaOrderInput {
  dispOrder: Int
  id: String!
}

input EmployeeFilterInput {
  email: String
  isAdmin: Boolean
  name: String
  status: String
}

input EmployeeInput {
  email: String!
  genderCode: String!
  isAdmin: Boolean!
  name: String!
}

input EmployeeInviteInput {
  email: String!
}

input LeadFilterInput {
  "ISO-8601"
  inquiryAtFrom: DateTime
  "ISO-8601"
  inquiryAtTo: DateTime
  locationId: String
  name: String
  source: String
  status: String
}

input LeadInput {
  email: String
  "ISO-8601"
  inquiryAt: DateTime
  locationId: String
  "ISO-8601"
  lostAt: DateTime
  lostReason: String
  name: String!
  note: String
  phone: String
  source: String
  status: String!
}

input LocationFilterInput {
  areaId: String
  name: String
  prefectureCode: String
}

input LocationInput {
  address: String
  areaId: String
  displayOrder: Int
  isDefault: Boolean
  name: String!
  prefectureCode: String
  zipCode: String
}

input MemberFilterInput {
  "ISO-8601"
  joinedAtFrom: Date
  "ISO-8601"
  joinedAtTo: Date
  locationId: String
  name: String
  source: String
  status: String
}

input MemberInput {
  address: String
  "ISO-8601"
  birthDate: Date
  email: String
  "ISO-8601"
  joinedAt: Date!
  leadId: String
  lineDisplayName: String
  locationId: String!
  name: String!
  note: String
  phone: String
  resignationNote: String
  resignationReasonCode: String
  "ISO-8601"
  resignedAt: Date
  source: String
  status: String!
}

input OwnAccountUpdateInput {
  currentPassword: String!
  name: String!
  newPassword: String
}

input Pagination {
  limit: Int
  offset: Int
  orderBy: String
  orderDirection: String
}
