allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@mantine/core@9.3.0'
  - '@mantine/dates@9.3.0'
  - '@mantine/form@9.3.0'
  - '@mantine/hooks@9.3.0'
  - '@mantine/notifications@9.3.0'
  - '@mantine/nprogress@9.3.0'
  - '@mantine/store@9.3.0'
  - lucide-react@1.41.0
  - playwright-core@1.63.0
  - playwright@1.63.0
